### ISSUE TITLE
multi call cache.Fetch int same frame  will miss requst callback

### ISSUE THREAD

**Issue by wenkuiwang** [mattak/Unicache#36]
I user fillcache in my application, when I need request multi file in same time , it just return one callback.
so I can not get all rezult.

**Comment by mattak** [comment]
@wenkuiwang 
Thanks for your reporting! 
I'm happy to see the message of user 😄 

If you have minimum test case (or code) of the issue, could you paste the code?
or I'll make the same situation and try by myself (maybe it'll take a little times).

**Comment by mattak** [comment]
Sorry, it seems hard to reproduce.
