### ISSUE TITLE
Add clear cache button on editor

### ISSUE THREAD

**Issue by agittm** [mattak/Unicache#37]

**Comment by mattak** [comment]
Thanks! I'll check it today

**Comment by mattak** [comment]
Hi @agittm !
I made a editor extension to remove current cache.
Unicache v0.2.0 contains this editor extension.

<img width="1086" alt="check_clear_button" src="https://user-images.githubusercontent.com/522828/39478392-485b4434-4d9d-11e8-9284-76566417642f.png">
<img width="226" alt="where" src="https://user-images.githubusercontent.com/522828/39478393-48810534-4d9d-11e8-82d8-b44162c04821.png">

But I have felt this extension was a little bit tricky, for example it's difficult to find & not easy to understand how to use this extension.
So I'll improve this extension!

**Comment by mattak** [comment]
IUnicacheGetter makes you to use unicache editor extension.

```csharp
diff --git a/Assets/Plugins/Unicache/Examples/Simple/SimpleComponents.cs b/Assets/Plugins/Unicache/Examples/Simple/SimpleComponents.cs
index f41ab86..680381b 100644
--- a/Assets/Plugins/Unicache/Examples/Simple/SimpleComponents.cs
+++ b/Assets/Plugins/Unicache/Examples/Simple/SimpleComponents.cs
@@ -6,13 +6,18 @@ using UniRx;
 
 namespace UnicacheExample.Simple
 {
-    public class SimpleComponents : MonoBehaviour
+    public class SimpleComponents : MonoBehaviour, IUnicacheGetter
     {
         public Button LoadButton;
+
         public Button ClearCacheButton;
+
         public Button ClearImageButton;
+
         public RawImage Image;
+
         public Text LoadingText;
+
         private IUnicache cache;
 
         void Start()
@@ -56,5 +61,10 @@ namespace UnicacheExample.Simple
         {
             this.cache.Clear();
         }
+
+        public IUnicache Cache
+        {
+            get { return this.cache; }
+        }
     }
 }
```

**Comment by agittm** [comment]
Oh so it's already there.
But yeah I feel that way is uneasy to understand.
