### ISSUE TITLE
Not working on Unity 2018.3.3f1

### ISSUE THREAD

**Issue by bwyyoung** [mattak/Unicache#44]
![screenshot_022119_015645_pm](https://user-images.githubusercontent.com/1365439/53146801-86154c80-35e0-11e9-98c7-e55ce50b25d6.jpg)

These are the errors. The project I am developing uses .NET 4.X for all platforms because of other libraries.
Please fix this compatibility issue.

**Comment by mattak** [comment]
@bwyyoung 

Thanks for reporting the issue 😄
Now the fix is included on Unicache v0.3.0.

**Comment by bwyyoung** [comment]
Thank you.
