### ISSUE TITLE
Support MemoryCache

### ISSUE THREAD

**Issue by mattak** [mattak/Unicache#7]
Currently only support for file cache. So implement memory cache.

**Comment by bnussey** [comment]
Hey @mattak have you thought about consolidating these? With other caching solutions, I have typically seen the following:

1. You download an image from a new URL.
2. It gets cached to memory and disk.
3. If you call the image in the same session, it is retrieved from the memory.
4. Let's say you re-run the app and then access the URL, it will check the memory, where the image won't be there, then it will check the disk, and get it from there. If not, it will download it.
5. The image stays in disk until expiration.

Let me know your thoughts.

Thanks!

**Comment by mattak** [comment]
@bnussey

Sorry for my late response. :bow:
I have no plan to consolidating these cache class now.
Because both of FileCache & MemoryCache is useful for debugging on some case.

But I think it's good to create other new cache class that using memory and disk with expiration.
Because `IUnicache` is interface, it's easy to replace by new implementation.

Sadly, I have no time to implement the feature at least now.
If you have a passion, PullRequest is always welcome!

Thanks!
